{% set name = "flytekitplugins-awsbatch" %}
{% set version = "1.2.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/flytekitplugins-awsbatch-{{ version }}.tar.gz
  sha256: 1ca995a92932df5ced93f450cf9d138531438e53a24b995aaa40709d973a9626

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - flytekit >=1.0.0b3,<1.2.0

test:
  imports:
    - flytekitplugins.awsbatch
  # commands:
  #   - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/flytekitplugins-awsbatch/
  summary: This package holds the AWS Batch plugins for flytekit
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  description: |
    AWS Batch plugin for Flytekit: `{{ name }}`

    PyPI: [https://pypi.org/project/flytekitplugins-awsbatch/](https://pypi.org/project/flytekitplugins-awsbatch/)

  doc_url: https://github.com/flyteorg/flytekit/tree/master/plugins
  dev_url: https://github.com/flyteorg/flytekit/tree/master/plugins/flytekit-aws-batch

extra:
  recipe-maintainers:
    - sugatoray
